import React, { useState, useEffect } from 'react';
import Icon from '../../../components/AppIcon';
import Button from '../../../components/ui/Button';
import Input from '../../../components/ui/Input';

const SEOOptimizationSection = ({ formData, aiDescription, onSEOChange, seoData }) => {
  const [autoGenerated, setAutoGenerated] = useState(false);

  useEffect(() => {
    if (formData?.name && aiDescription && !autoGenerated) {
      generateSEOData();
      setAutoGenerated(true);
    }
  }, [formData?.name, aiDescription]);

  const generateSEOData = () => {
    const keywords = generateKeywords(formData, aiDescription);
    const metaDescription = generateMetaDescription(formData, aiDescription);
    const title = generateSEOTitle(formData);

    onSEOChange({
      title,
      metaDescription,
      keywords: keywords?.join(', '),
      slug: generateSlug(formData?.name)
    });
  };

  const generateKeywords = (data, description) => {
    const baseKeywords = [
      'handmade',
      'indian craft',
      'traditional',
      'artisan made',
      'authentic'
    ];

    const categoryKeywords = {
      pottery: ['pottery', 'ceramic', 'clay', 'earthenware', 'handmade pottery'],
      textiles: ['textile', 'fabric', 'handwoven', 'traditional fabric', 'indian textile'],
      jewelry: ['jewelry', 'ornament', 'traditional jewelry', 'handcrafted jewelry'],
      woodwork: ['woodwork', 'wooden craft', 'carved wood', 'traditional woodwork'],
      metalwork: ['metalwork', 'brass', 'metal craft', 'traditional metalwork']
    };

    const nameKeywords = data?.name ? data?.name?.toLowerCase()?.split(' ') : [];
    const categorySpecific = categoryKeywords?.[data?.category] || [];

    return [...baseKeywords, ...categorySpecific, ...nameKeywords]?.slice(0, 15);
  };

  const generateMetaDescription = (data, description) => {
    const shortDesc = description ? description?.substring(0, 120) : '';
    return `${shortDesc}... Authentic handmade ${data?.category || 'craft'} by Indian artisans. Shop traditional crafts online.`;
  };

  const generateSEOTitle = (data) => {
    return `${data?.name || 'Handmade Craft'} - Traditional Indian ${data?.category || 'Artisan'} | ArtisanConnect`;
  };

  const generateSlug = (name) => {
    return name ? name?.toLowerCase()?.replace(/[^a-z0-9]+/g, '-')?.replace(/(^-|-$)/g, '') : '';
  };

  const handleSEOChange = (field, value) => {
    onSEOChange({
      ...seoData,
      [field]: value
    });
  };

  const regenerateSEO = () => {
    generateSEOData();
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center space-x-2 mb-6">
        <div className="w-8 h-8 bg-primary text-primary-foreground rounded-full flex items-center justify-center text-sm font-semibold">
          3
        </div>
        <h3 className="text-lg font-semibold text-foreground">SEO Optimization</h3>
      </div>
      {/* Auto-generate Button */}
      <div className="flex flex-col sm:flex-row gap-4 items-start sm:items-center justify-between p-4 bg-muted/50 rounded-lg border border-border">
        <div className="flex-1">
          <h4 className="font-medium text-foreground mb-1">SEO Auto-Generation</h4>
          <p className="text-sm text-muted-foreground">
            Generate SEO-optimized title, description, and keywords based on your product details
          </p>
        </div>
        <Button
          onClick={regenerateSEO}
          iconName="RefreshCw"
          iconPosition="left"
          variant="outline"
          size="sm"
        >
          Regenerate SEO
        </Button>
      </div>
      <div className="grid grid-cols-1 gap-6">
        {/* SEO Title */}
        <Input
          label="SEO Title"
          type="text"
          placeholder="Product title for search engines"
          value={seoData?.title || ''}
          onChange={(e) => handleSEOChange('title', e?.target?.value)}
          description={`${(seoData?.title || '')?.length}/60 characters (recommended)`}
          maxLength="60"
        />

        {/* Meta Description */}
        <div>
          <label className="block text-sm font-medium text-foreground mb-2">
            Meta Description
          </label>
          <textarea
            className="w-full px-3 py-2 border border-border rounded-lg focus:outline-none focus:ring-2 focus:ring-ring focus:border-transparent resize-none"
            rows="3"
            placeholder="Brief description for search engine results"
            value={seoData?.metaDescription || ''}
            onChange={(e) => handleSEOChange('metaDescription', e?.target?.value)}
            maxLength="160"
          />
          <p className="text-xs text-muted-foreground mt-1">
            {(seoData?.metaDescription || '')?.length}/160 characters (recommended)
          </p>
        </div>

        {/* Keywords */}
        <div>
          <label className="block text-sm font-medium text-foreground mb-2">
            Keywords
          </label>
          <textarea
            className="w-full px-3 py-2 border border-border rounded-lg focus:outline-none focus:ring-2 focus:ring-ring focus:border-transparent resize-none"
            rows="2"
            placeholder="Comma-separated keywords"
            value={seoData?.keywords || ''}
            onChange={(e) => handleSEOChange('keywords', e?.target?.value)}
          />
          <p className="text-xs text-muted-foreground mt-1">
            Separate keywords with commas. Focus on relevant terms your customers might search for.
          </p>
        </div>

        {/* URL Slug */}
        <Input
          label="URL Slug"
          type="text"
          placeholder="product-url-slug"
          value={seoData?.slug || ''}
          onChange={(e) => handleSEOChange('slug', e?.target?.value)}
          description="URL-friendly version of your product name"
        />
      </div>
      {/* SEO Preview */}
      {seoData?.title && seoData?.metaDescription && (
        <div className="space-y-4">
          <h4 className="font-medium text-foreground">Search Engine Preview</h4>
          <div className="p-4 bg-card border border-border rounded-lg">
            <div className="space-y-2">
              <h5 className="text-lg text-blue-600 hover:underline cursor-pointer">
                {seoData?.title}
              </h5>
              <p className="text-sm text-green-700">
                artisanconnect.com/products/{seoData?.slug}
              </p>
              <p className="text-sm text-gray-600">
                {seoData?.metaDescription}
              </p>
            </div>
          </div>
        </div>
      )}
      {/* SEO Tips */}
      <div className="p-4 bg-accent/10 border border-accent/20 rounded-lg">
        <div className="flex items-start space-x-3">
          <Icon name="Lightbulb" size={20} className="text-accent mt-0.5" />
          <div>
            <h5 className="font-medium text-foreground mb-2">SEO Tips</h5>
            <ul className="text-sm text-muted-foreground space-y-1">
              <li>• Keep titles under 60 characters for better visibility</li>
              <li>• Write compelling meta descriptions under 160 characters</li>
              <li>• Use relevant keywords that customers actually search for</li>
              <li>• Include your craft category and "handmade" in keywords</li>
              <li>• Make URLs simple and descriptive</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
};

export default SEOOptimizationSection;