/**
 * Gemini API Integration for Content Generation
 * Direct client-side integration with Google's Gemini AI API
 */

// For demo purposes, using a mock API key. In production, this should be handled by your backend.
const GEMINI_API_KEY = import.meta.env.VITE_GEMINI_API_KEY || 'AIzaSyC2ArZm2BBsfeW5HhgK21Ui9Tr19H1RyY0'; // Hardcoded fallback for testing
const GEMINI_API_URL = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent';

// Debug log to check if API key is loaded
console.log('Gemini API Key loaded:', GEMINI_API_KEY !== 'demo-key' ? 'Yes' : 'No (using demo-key)');
console.log('API Key first 10 chars:', GEMINI_API_KEY ? GEMINI_API_KEY.substring(0, 10) + '...' : 'Not found');
console.log('Full API Key check:', GEMINI_API_KEY);
console.log('Environment check:', import.meta.env.VITE_GEMINI_API_KEY);

/**
 * Generate marketing content using Gemini AI
 * @param {Array} products - Array of selected products
 * @param {string} platform - Target social media platform
 * @param {string} tone - Content tone (professional, casual, enthusiastic)
 * @returns {Promise<Object>} Generated content object
 */
export const generateMarketingContent = async (products, platform = 'instagram', tone = 'enthusiastic') => {
  try {
    // Create detailed product descriptions for the prompt
    const productDescriptions = products.map(product => {
      return `Product: ${product.name}
Price: ₹${product.price.toLocaleString('en-IN')}
Category: ${product.category || 'Handcrafted Item'}
Description: ${product.description}
Materials: ${product.materials || 'Traditional materials'}
Artisan Specialty: ${product.specialty || 'Traditional craftsmanship'}`;
    }).join('\n\n');

    // Create a highly detailed prompt for Gemini
    const prompt = `Create engaging ${platform} marketing content for this product:

PRODUCT: ${products[0]?.name}
PRICE: ₹${products[0]?.price?.toLocaleString('en-IN')}
DESCRIPTION: ${products[0]?.description}
MATERIALS: ${products[0]?.materials?.join(', ') || 'traditional materials'}
ARTISAN: ${products[0]?.artisan?.firstName} ${products[0]?.artisan?.lastName} from ${products[0]?.artisan?.location?.city}, ${products[0]?.artisan?.location?.state}

Write a compelling ${tone} ${platform} caption that:
- Mentions the specific product name and exact price
- Highlights the craftsmanship and materials
- Tells the artisan's story
- Uses appropriate ${platform} style and tone
- Includes a call-to-action

Write 150-200 words maximum. Make it engaging and authentic.`;

    // Check if we have a real API key
    if (GEMINI_API_KEY === 'demo-key' || !GEMINI_API_KEY) {
      console.log('No valid Gemini API key found, using mock content');
      return generateMockContent(products, platform, tone);
    }

    console.log('Making real Gemini API call for products:', products.map(p => p.name));
    console.log('Platform:', platform, 'Tone:', tone);
    console.log('Full prompt being sent to Gemini:', prompt.substring(0, 200) + '...');

    // Make actual API call to Gemini
    const response = await fetch(`${GEMINI_API_URL}?key=${GEMINI_API_KEY}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        contents: [{
          parts: [{
            text: prompt
          }]
        }],
        generationConfig: {
          temperature: 0.7,
          topK: 40,
          topP: 0.95,
          maxOutputTokens: 2048, // Increased from 1024 to 2048
        }
      })
    });

    console.log('Gemini API Response Status:', response.status);
    
    if (!response.ok) {
      const errorText = await response.text();
      console.error('Gemini API Error Details:', errorText);
      throw new Error(`Gemini API error: ${response.status} - ${errorText}`);
    }

    const data = await response.json();
    console.log('Gemini API Response Data:', data);
    console.log('Response structure check:');
    console.log('- Has candidates:', !!data.candidates);
    console.log('- Candidates length:', data.candidates?.length);
    console.log('- First candidate:', data.candidates?.[0]);
    
    // Check if the response has the expected structure
    if (!data.candidates || data.candidates.length === 0) {
      console.error('No candidates in response:', data);
      throw new Error('No content generated by Gemini API');
    }
    
    const candidate = data.candidates[0];
    console.log('Candidate structure:', candidate);
    console.log('Finish reason:', candidate.finishReason);
    
    if (!candidate.content || !candidate.content.parts || candidate.content.parts.length === 0) {
      console.error('Invalid candidate structure:', candidate);
      
      // If it's a MAX_TOKENS issue, try to handle it gracefully
      if (candidate.finishReason === 'MAX_TOKENS') {
        console.warn('Response was truncated due to token limit, falling back to mock content');
        return generateMockContent(products, platform, tone);
      }
      
      throw new Error('Invalid content structure from Gemini API');
    }
    
    const generatedText = candidate.content.parts[0].text;
    console.log('Generated Text from Gemini:', generatedText);
    
    // Since we're getting natural text (not JSON), structure it properly
    const content = {
      caption: generatedText.trim(),
      hashtags: generateHashtagsForProduct(products[0], platform),
      bestTime: getBestPostingTime(platform),
      engagement: getEngagementTip(platform, products[0]),
      callToAction: `Shop this amazing ${products[0]?.name} for ₹${products[0]?.price?.toLocaleString('en-IN')}!`,
      tips: getMarketingTips(platform, products[0])
    };
    
    return {
      ...content,
      generatedAt: new Date().toISOString(),
      platform,
      products: products.map(p => ({ id: p.id, name: p.name }))
    };

  } catch (error) {
    console.error('Error generating content with Gemini:', error);
    // Fallback to mock content
    return generateMockContent(products, platform, tone);
  }
};

/**
 * Generate relevant hashtags for a product
 */
const generateHashtagsForProduct = (product, platform) => {
  const baseHashtags = ['#HandmadeInIndia', '#TraditionalCrafts', '#SupportLocal', '#AuthenticCrafts'];
  
  // Safely access product properties
  const categoryHashtag = product?.category ? `#${product.category.replace(/\s+/g, '')}` : '';
  const materialHashtags = product?.materials?.map(m => `#${m.replace(/\s+/g, '')}`).slice(0, 2) || [];
  const locationHashtag = product?.artisan?.location?.state ? `#${product.artisan.location.state.replace(/\s+/g, '')}` : '';
  
  const allHashtags = [
    ...baseHashtags,
    categoryHashtag,
    ...materialHashtags,
    locationHashtag,
    '#ArtisanMade',
    '#CulturalHeritage'
  ].filter(Boolean);
  
  return allHashtags.slice(0, 10);
};

/**
 * Get best posting time for platform
 */
const getBestPostingTime = (platform) => {
  const times = {
    instagram: '7:00 PM - 9:00 PM IST (Peak engagement time)',
    facebook: '8:00 PM - 10:00 PM IST (Family time browsing)',
    twitter: '12:00 PM - 2:00 PM IST (Lunch break activity)'
  };
  return times[platform] || times.instagram;
};

/**
 * Get engagement tip for platform and product
 */
const getEngagementTip = (platform, product) => {
  const productName = product?.name || 'this handcrafted item';
  const materials = product?.materials?.join(' and ') || 'traditional materials';
  
  const tips = {
    instagram: `Use high-quality photos of the ${productName} and engage with craft enthusiasts in comments`,
    facebook: `Share the artisan story and encourage users to share their own traditional craft experiences`,
    twitter: `Create threads about the ${materials} crafting process`
  };
  return tips[platform] || tips.instagram;
};

/**
 * Get marketing tips for platform and product
 */
const getMarketingTips = (platform, product) => {
  const productName = product?.name || 'handcrafted item';
  const artisanName = product?.artisan?.firstName || 'the craftsperson';
  
  const baseTips = [
    `Highlight the handcrafted nature of ${productName}`,
    `Share behind-the-scenes content of artisan ${artisanName}`,
    `Use authentic photography showing texture and details`,
    `Engage with traditional craft communities`
  ];
  return baseTips.slice(0, 3);
};

/**
 * Parse text response to structured content if JSON parsing fails
 */
const parseTextToContent = (text, products, platform) => {
  // Simple text parsing fallback
  const lines = text.split('\n').filter(line => line.trim());
  
  return {
    caption: text.substring(0, 300) + '...',
    hashtags: ['#HandmadeInIndia', '#ArtisanCrafts', '#TraditionalArt', '#SupportLocal'],
    bestTime: '7:00 PM - 9:00 PM IST',
    engagement: 'Generated from AI text response',
    callToAction: 'Discover authentic craftsmanship!',
    tips: ['Use high-quality images', 'Engage with followers', 'Post consistently'],
    generatedAt: new Date().toISOString(),
    platform,
    products: products.map(p => ({ id: p.id, name: p.name }))
  };
};

/**
 * Generate mock content when Gemini API is not available
 */
const generateMockContent = (products, platform, tone) => {
  const productNames = products.map(p => p.name).join(', ');
  const totalValue = products.reduce((sum, p) => sum + p.price, 0);
  
  const platformSpecificContent = {
    instagram: {
      caption: `✨ Discover the magic of authentic Indian craftsmanship! ✨

${products.length > 1 ? 'These stunning pieces showcase' : 'This beautiful piece showcases'} the incredible talent of our artisans: ${productNames}

🎨 Each item is lovingly handcrafted using traditional techniques passed down through generations
🌟 Supporting local artisans and preserving cultural heritage
💫 Bringing you authentic, one-of-a-kind treasures

Starting from ₹${Math.min(...products.map(p => p.price)).toLocaleString('en-IN')} - Shop now and own a piece of India's rich artistic legacy!

#ArtisanMade #HandcraftedInIndia #TraditionalCrafts #SupportLocal`,
      hashtags: ['#HandmadeInIndia', '#ArtisanCrafts', '#TraditionalArt', '#SupportLocal', '#IndianHeritage', '#AuthenticCrafts'],
      bestTime: '7:00 PM - 9:00 PM IST',
      engagement: 'High - Visual content performs well',
      callToAction: 'Shop now and celebrate Indian craftsmanship!',
      tips: ['Use high-quality product photos', 'Post during evening hours for maximum engagement', 'Engage with comments to build community']
    },
    facebook: {
      caption: `Celebrate the beauty of handcrafted Indian art with our exclusive collection!

We're proud to showcase ${productNames} - each piece tells a story of skill, tradition, and passion.

🔹 Handcrafted by skilled artisans
🔹 Authentic traditional techniques
🔹 Supporting local communities
🔹 Preserving cultural heritage

Collection value: ₹${totalValue.toLocaleString('en-IN')}

Discover these treasures and bring home the essence of India's rich craftsmanship tradition.`,
      hashtags: ['#IndianCrafts', '#ArtisanMade', '#TraditionalArt', '#HandmadeInIndia', '#CulturalHeritage'],
      bestTime: '8:00 PM - 10:00 PM IST',
      engagement: 'Medium to High - Share-worthy content',
      callToAction: 'Explore our collection and find your perfect piece!',
      tips: ['Include product links in comments', 'Encourage sharing to reach wider audience', 'Use Facebook Events for craft exhibitions']
    },
    twitter: {
      caption: `🧵 Authentic ${productNames} - where tradition meets artistry!

Each piece: Handcrafted ✨ | Heritage-inspired 🎨 | Artisan-made 👐

Starting ₹${Math.min(...products.map(p => p.price)).toLocaleString('en-IN')}

#MadeInIndia #ArtisanCrafts`,
      hashtags: ['#MadeInIndia', '#ArtisanCrafts', '#TraditionalArt', '#HandcraftedGoods', '#SupportArtisans'],
      bestTime: '12:00 PM - 2:00 PM IST',
      engagement: 'Medium - Use trending hashtags',
      callToAction: 'Thread below 👇 Discover our collection!',
      tips: ['Keep tweets concise', 'Use trending hashtags', 'Create tweet threads for storytelling', 'Engage in craft-related conversations']
    }
  };

  const content = platformSpecificContent[platform] || platformSpecificContent.instagram;
  
  return {
    ...content,
    generatedAt: new Date().toISOString(),
    platform,
    tone,
    products: products.map(p => ({ id: p.id, name: p.name, price: p.price }))
  };
};